version: '3.9'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    networks:
      - network

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - network

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DB_HOST=postgres
      - DB_NAME=docker
      - POOL_MODE=transaction
      - ADMIN_USERS=docker
      - AUTH_TYPE=plain
    ports:
      - "6432:5432"
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge